/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot
// GetJobDetailRspAllOf struct for GetJobDetailRspAllOf
type GetJobDetailRspAllOf struct {
	Data Job `json:"data,omitempty"`
}
