/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot-api-go
// IntentLevelTagDetails struct for IntentLevelTagDetails
type IntentLevelTagDetails struct {
	Code int32 `json:"code,omitempty"`
	Name string `json:"name,omitempty"`
}
