/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot
// PhoneDeadArea struct for PhoneDeadArea
type PhoneDeadArea struct {
	City string `json:"city,omitempty"`
	Prov string `json:"prov,omitempty"`
}
