/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot-api-go
// GetIntentLevelTagRspAllOf struct for GetIntentLevelTagRspAllOf
type GetIntentLevelTagRspAllOf struct {
	Data IntentLevelTag `json:"data,omitempty"`
}
