/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot-api-go
// RobotCallJobInactiveTimeList struct for RobotCallJobInactiveTimeList
type RobotCallJobInactiveTimeList struct {
	StartTime string `json:"startTime,omitempty"`
	EndTime string `json:"endTime,omitempty"`
}
