/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot-api-go
// GetSubAccountIsvReq 
type GetSubAccountIsvReq struct {
	TenantSign string `json:"tenantSign"`
	PhoneNumber string `json:"phoneNumber"`
}
