/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot-api-go
// GetJobStatsInfoListRspAllOf struct for GetJobStatsInfoListRspAllOf
type GetJobStatsInfoListRspAllOf struct {
	Data []GetJobStatsInfoListRspAllOfData `json:"data,omitempty"`
}
