/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot-api-go
// TotalDialogFlowListRspAllOf struct for TotalDialogFlowListRspAllOf
type TotalDialogFlowListRspAllOf struct {
	Data DialogFlowPage `json:"data,omitempty"`
}
