/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot
// Industry struct for Industry
type Industry struct {
	Name string `json:"name,omitempty"`
	Desc string `json:"desc,omitempty"`
}
