/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot-api-go
// GetUsedIntentLevelTagListRspAllOf struct for GetUsedIntentLevelTagListRspAllOf
type GetUsedIntentLevelTagListRspAllOf struct {
	Data []IntentLevelTag `json:"data,omitempty"`
}
