/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot-api-go
// GetPhoneListRspAllOf struct for GetPhoneListRspAllOf
type GetPhoneListRspAllOf struct {
	Data []Phone `json:"data,omitempty"`
}
