/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot
// DialogFlowStep struct for DialogFlowStep
type DialogFlowStep struct {
	Title string `json:"title,omitempty"`
	DialogFlowNodes []DialogFlowNode `json:"dialogFlowNodes,omitempty"`
}
