/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot
// DialogFlowNode 流程节点
type DialogFlowNode struct {
	Label string `json:"label,omitempty"`
	Title string `json:"title,omitempty"`
	Context string `json:"context,omitempty"`
	PrefixRecordUrl string `json:"prefixRecordUrl,omitempty"`
}
