/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot
// DialogFlowListAllOf struct for DialogFlowListAllOf
type DialogFlowListAllOf struct {
	Data []DialogFlow `json:"data,omitempty"`
}
