/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot-api-go
// InlineObject struct for InlineObject
type InlineObject struct {
	// 任务Id
	RobotCallJobId int64 `json:"robotCallJobId"`
}
