/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot-api-go
// JobUpdateRspAllOf struct for JobUpdateRspAllOf
type JobUpdateRspAllOf struct {
	Data JobUpdateRspAllOfData `json:"data,omitempty"`
}
