/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot
// GetIdAndNamePairListRspAllOf struct for GetIdAndNamePairListRspAllOf
type GetIdAndNamePairListRspAllOf struct {
	Data PolicyGroupIdAndNamePair `json:"data,omitempty"`
}
