/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot-api-go
// RobotKnowledge 问答知识
type RobotKnowledge struct {
	Title string `json:"title,omitempty"`
	Answers []DialogFlowNode `json:"answers,omitempty"`
}
