/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot
// GetPolicyGroupListRspAllOf struct for GetPolicyGroupListRspAllOf
type GetPolicyGroupListRspAllOf struct {
	Data PolicyGroup `json:"data,omitempty"`
}
