/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot-api-go
// InterceptListRspAllOf struct for InterceptListRspAllOf
type InterceptListRspAllOf struct {
	Data []CallIntercept `json:"data,omitempty"`
}
