/*
 * Tanyi Bot open api
 *
 * tanyibot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tanyibot-api-go
// InlineObject1 struct for InlineObject1
type InlineObject1 struct {
	// 任务Id
	RobotCallJobId int64 `json:"robotCallJobId,omitempty"`
}
